### ISSUE TITLE
Apache Server Deployment

### ISSUE THREAD

**Issue by hasretja** [carlosemv/camera-app#2]
Helo carlos

I developed a project based on the code and when I try to run it on an apache server the camera is not working and I get the following error. Can you help me?

[Sun Apr 04 11:57:54.230397 2021] [wsgi:error] [pid 1943:tid 140166340073216] [client 192.168.1.28:61834] mod_wsgi (pid=1943): Exception occurred processing WSGI script '/var/www/webApp/webapp.wsgi'., referer: http://192.168.1.34/index/
[Sun Apr 04 11:57:54.231430 2021] [wsgi:error] [pid 1943:tid 140166340073216] [client 192.168.1.28:61834] Traceback (most recent call last):, referer: http://192.168.1.34/index/
[Sun Apr 04 11:57:54.231472 2021] [wsgi:error] [pid 1943:tid 140166340073216] [client 192.168.1.28:61834]   File "/usr/local/lib/python3.8/dist-packages/werkzeug/wsgi.py", line 506, in __next__, referer: http://192.168.1.34/index/
[Sun Apr 04 11:57:54.231533 2021] [wsgi:error] [pid 1943:tid 140166340073216] [client 192.168.1.28:61834]     return self._next(), referer: http://192.168.1.34/index/
[Sun Apr 04 11:57:54.231600 2021] [wsgi:error] [pid 1943:tid 140166340073216] [client 192.168.1.28:61834]   File "/usr/local/lib/python3.8/dist-packages/werkzeug/wrappers/base_response.py", line 45, in _iter_encoded, referer: http://192.168.1.34/index/
[Sun Apr 04 11:57:54.231606 2021] [wsgi:error] [pid 1943:tid 140166340073216] [client 192.168.1.28:61834]     for item in iterable:, referer: http://192.168.1.34/index/
[Sun Apr 04 11:57:54.231620 2021] [wsgi:error] [pid 1943:tid 140166340073216] [client 192.168.1.28:61834]   File "/var/www/webApp/webApp/__init__.py", line 39, in gen, referer: http://192.168.1.34/index/
[Sun Apr 04 11:57:54.231624 2021] [wsgi:error] [pid 1943:tid 140166340073216] [client 192.168.1.28:61834]     yield (b'--frame\\r\\n', referer: http://192.168.1.34/index/
[Sun Apr 04 11:57:54.231642 2021] [wsgi:error] [pid 1943:tid 140166340073216] [client 192.168.1.28:61834] TypeError: can't concat NoneType to bytes, referer: http://192.168.1.34/index/

Thanks.

**Comment by carlosemv** [comment]
Hi!

That error has to do with OpenCV not being able to capture video.

**Comment by carlosemv** [comment]
Hi,

That error has to do with OpenCV not being able to capture video.
I suggest taking a look at the documentation for the OpenCV VideoCapture function to adapt it to your use case.
Best of luck!
